CREATE TABLE incident_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id VARCHAR(32) NOT NULL UNIQUE,
    service_id VARCHAR(64) NOT NULL,
    severity INTEGER NOT NULL,
    summary VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL
);

CREATE INDEX idx_incident_tickets_status ON incident_tickets (status);
CREATE INDEX idx_incident_tickets_service_id ON incident_tickets (service_id);
CREATE INDEX idx_incident_tickets_severity ON incident_tickets (severity);
