spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:incidentops}
spring.datasource.username=${POSTGRES_USER:incidentops}
spring.datasource.password=${POSTGRES_PASSWORD:incidentops}
spring.jpa.show-sql=false
spring.cache.type=redis
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

incidentops.integrations.redis.host=${REDIS_HOST:redis}
incidentops.integrations.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
incidentops.security.api-key=${INCIDENTOPS_API_KEY:docker-local-api-key}
incidentops.security.signing-secret=${INCIDENTOPS_SIGNING_SECRET:docker-local-signing-secret}
incidentops.messaging.kafka.topic=${INCIDENTOPS_KAFKA_TOPIC:incident-events}
incidentops.messaging.kafka.group-id=${INCIDENTOPS_KAFKA_GROUP_ID:incidentops-docker}
incidentops.async.executor.core-pool-size=${INCIDENTOPS_ASYNC_CORE_POOL_SIZE:4}
incidentops.async.executor.max-pool-size=${INCIDENTOPS_ASYNC_MAX_POOL_SIZE:16}
incidentops.async.executor.queue-capacity=${INCIDENTOPS_ASYNC_QUEUE_CAPACITY:200}
incidentops.async.executor.thread-name-prefix=${INCIDENTOPS_ASYNC_THREAD_NAME_PREFIX:incidentops-docker-async-}
